version: '3.3'
services:
  db:
    image: postgres
    ports:
      - 54322:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: data

volumes:
  postgres-data:
